<?php include('header.php');?>




        <!-- Header Start -->
        <div class="container-fluid header  p-0" style="background:#991403;">
            <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
                <div class="col-md-6 p-5 mt-lg-5">
                    <h1 class="display-5 animated fadeIn mb-4 text-white">Legend - Detailed</h1> 
                        <nav aria-label="breadcrumb animated fadeIn">
                        <ol class="breadcrumb text-uppercase">
                            <li class="breadcrumb-item "><a href="<?php echo base_url('KadamController/index');?>" class="text-white">Home</a></li>
                            <li class="breadcrumb-item text-body active" aria-current="page"><a href="<?php echo base_url('KadamController/Legend');?>" class="text-white">Legend - Detailed</a></li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 animated fadeIn">
                    <img class="img-fluid" src="<?php echo base_url();?>img/templeslider1.jpg" alt="">
                </div>
            </div>
        </div>
        <!-- Header End -->


             <div class="container-xxl py-5">
            <div class="container">
                <h1 class="mb-3 text-primary">Legend - Detailed</h1>
                <div class="row g-0 gx-5 align-items-end">
                     <div class="col-lg-12">
                        <div class="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s">
                            
                            <p style="text-align:justify;"><img alt="" src="<?php echo base_url();?>img/l1.png" style="float:right; height:144px; margin:10px; width:180px" />The origin of Kadampuzha Temple is associated with the Mahabharatha, the ancient Indian myth, considered to be the greatest story ever told. Mahabharatha has 18 Parvas or Books, each dealing with a specific period of the epic and the legend of Kadampuzha figures in the 3rd Parva known as the Aranyak Parva or Van Parva. During their 5th year of exile, Arjuna, as advised by Sree Krishna, took leave of his brothers and his wife Droupathi, in order to seek and obtain the knowledge of the Divya Astras, or celestial missiles that would be absolutely necessary in the battle that was imminent between the Paandavas, and their cousins, the Kauravas.These Divya Astras could only be obtained by performing the greatest penance or “Tapas” or “very deep meditation combined with self scarifies that tests human endurance” that any living being could do and even then they would be given only to those who are on the side of Dharma since, once used, the entire world would perish by their supreme destructibility.Arjuna particularly wanted Pashupathastra, the supreme weapon of Pashupathi, the protector of all organisms, Load Siva.Arjuna started his Shivapuja at the foothills of Himalayas near the banks of the mighty river Ganges. Seeing the intensity of his Tapas, Lord Shiva and his wife Parvathy Devi wanted to test the loyalty and depth of his commitment.<img alt="" src="<?php echo base_url();?>img/l2.png" style="float:left; height:144px; margin:10px; width:180px" /> 
                            They transformed themselves into a Kirata King and wife and came to where Arjuna was doing his Tapas, standing on the toe of his right foot, hands raised in pranam to the heavens, high above his head and with air as his only sustenance, chanting manthras to appease Lord Shiva. Lord Shiva was very happy with his disciple, yet knowing that Arjuna’s ego was still very much of a hindrance to his achieving greatness, decided to test him and to wrest out his ego in the process. Parvathy Devi, knowing fully well the strength and temperament of both, was apprehensive.It was at this time that Mookasur, a fierce demon had come to seek out and kill Arjuna at the behest of Dhuryodhana, the Kowrava King. Taking the shape of a wild boar, he charged towards Arjuna who was in deep meditation.   </p>
                            <p style="text-align:justify;">The warrior instincts ingrained into the very core of Arjuna took over and in a flash he came out of his meditation, took his bow, made tight his bow string and with a single arrow, pierced the wild boar through its mouth. The very same instant, Lord Shiva, disguised as a Kiratha King, also let loose with an arrow that pierced the wild boar from its hindquarters and the wild boar changed back to Mookasur and lay breathing his last. The Kiratha King acted very annoyed with Arjuna for having interfered with his kill. Arjuna with disdain replied that it was his arrow that claimed the kill and what could the puny arrows of a wild man could do to such an asura, as it was now revealed.<img alt="" src="<?php echo base_url();?>img/l3.png" style="float:right; height:144px; margin:10px; width:180px" />The Kiratha King got very offended and started taunting Arjuna prodding him to a fight. Initially Arjuna tried evading a fight with this wild man yet when the Kiratha King started abusing his brothers, mother and Panchali, he found it hard to restrain himself. The proverbial end of his temperamental tether came when the Kiratha King started insulting the very Lord that Arjuna was paying penance to, Lord Siva. With that, a terrible fight ensued between the two with none giving any quarter. Parvathy started getting worried at the ferocity of the fight and she could not foresee an end to the fight without either one getting grievously hurt. She ran to each, beseeching to stop fighting but that only resulted in enraging them further. Deep wounds started making telling effect on both the great warriors and Parvathy now became desperate knowing that if her Lord got really angry, there was no force in Heaven or Earth that could withstand the His wrath. When her desperate pleas failed to dissuade Arjuna, she turned all his arrows to Thechi flowers.Though bewildered for a moment, Arjuna, the unmatched warrior that he is, started shaping arrows of the flowers. Each flower multiplied by thousands when each left his bow and soon, Lord Shiva was completely covered by Thechi flowers.  </p>
                            <p style="text-align:justify;">Soon the flowers also ran out. Arjuna then tried attacking the Kiratha King with his bow and that too was soon snatched away and disdainfully thrown aside. Weapon less, Arjuna started punching the Kiratha King with his bare hands and then the King caught his hands and as easily as a man would a puppet, flung him to a great height, soon to come crashing down on the unmerciful, hard earth. As he lay stunned and helpless, Arjuna finally realized that the wild one he was fighting with was no ordinary being but someone a lot superior to his own strength. Humbled, he gathered his Tapsya to him and made a small Siva Linga out of the mud and started adorning it with whatever leaves and flowers he could reach, opening out his being to Lord Shiva. To his utter amazement, he found all his offerings to his impromptu deity falling at the feet of the Kiratha King and the light finally dawned in his mind. He finally understood what the wife of the Kiratha King was trying to tell him. That the person he was fighting, the wild one he was so disdainful of, the one that so easily withstood his superior onslaught with disdain was none other than the Powerful One he was so desperately seeking, the Lord of all Organisms, Pashupathi. Filled with remorse and deep anguish, he prostrated at the feet of his beloved Lord, washing his feet with copious tears, begging forgiveness. Lord Shiva, on his part was so moved with his favourite disciple’s absolute devotion, valour and obvious remorse that he embraced Arjuna with unsuppressed fondness and Parvathy Devi too was overwhelmed with her maternal instincts, bestowing Arjuna with boons. Then Pashupathi imparted the knowledge of the great Pashupathastra to Arjuna and the Gods and Apsaras showered flowers on Arjuna in anticipation of the forthcoming victory over evil.</p>
                            <p style="text-align:justify;">Arjuna, the sufferings of his deep penance magically removed, took leave of his beloved Lord and the Divine Mother. Lord Shiva and Parvathy, so caught up in the momentous happenings and the intensity of emotions, decided to stay on as the Kiratha King and his wife for a while longer to wander around, enjoying the beauty of the land so rich. Soon it was time for them to return to Kilas, the Heavenly Abode of Lord Shiva. They were resting then at a place so filled with lush greenery and the songs of numerous birds. Coconut palms laden with fruits kept nodding in tune to the birdsongs in the caressing breeze. Parvathy requested her Lord to give her some water to quench her thirst and the Lord shot an arrow deep into the earth to summon Ganga. Having quenched her thirst and being satiated with the events of the previous days and suffused with happiness, Parvathy requested her Lord that the place they were then be known as her place, where whatever boons will be granted to those who come beseeching with a pure heart. She also requested that her Lord also make his presence felt in a stone before her.Since Parvathy kept beseeching her lord to stop fighting and to grand Arjuna the boons that he deserves, she came to be called as Thwaritha Devi or One who prompts the Lord to bestow boons easily to whoever beseeches the Lord with utmost humility.The “Chitanyam” or the Divine Presence of the Thwaritha Devi was thus attached to the hole that Lord Shiva’s arrow made and the Shiva Chitanyam or the Divine Presence of Lord Shiva was attached to the stone West of the hole. And thus they remained till that auspicious day when Adi Shankara happened to discover their presence and consecrate a temple here.</p>
                            
                        </div>
                    </div>
                    
                   
                  
                </div>
   </div>
    </div>
        
<?php include('footer.php');?>