<?php
				class Immigration_Model extends CI_Model {

				 public function insertuserdetails(){

				 $formarray=array('visa_app' => $this->input->post('visa_app'),
							      'un_date' => $this->input->post('un_date'),
							      'notice_period' => $this->input->post('notice_period'),
							       'plan_date' => $this->input->post('plan_date'),
							       'un_date' => $this->input->post('un_date'),
							      'tel_no' => $this->input->post('tel_no'),
							       'email_id' => $this->input->post('email_id'),
							       'given_name' => $this->input->post('given_name'),
							       'last_name' => $this->input->post('last_name'),
							       'r1' => $this->input->post('r1'),
							       'giv_name1' => $this->input->post('giv_name1'),
							       'las_name1' => $this->input->post('las_name1'),
							       'status' => $this->input->post('status'),
							       'addr1' => $this->input->post('addr1'),
							       'addr2' => $this->input->post('addr2'),
							       'city' => $this->input->post('city'),
							       'state' => $this->input->post('state'),
							       'country' => $this->input->post('country'),
							      'postcode' => $this->input->post('postcode'),
							       'c1' => $this->input->post('c1'),
							       'addr3' => $this->input->post('addr3'),
							      'city1' => $this->input->post('city1'),
							       'state1' => $this->input->post('state1'),
							       'country1' => $this->input->post('country1'),
							      'postcode1' => $this->input->post('postcode1'),
							       'long_live' => $this->input->post('long_live'),
							       'addrr1' => $this->input->post('addrr1'),
							      'addrr2' => $this->input->post('addrr2'),
							       'city2' => $this->input->post('city2'),
							       'state2' => $this->input->post('state2'),
							      'country2' => $this->input->post('country2'),
							       'postcode2' => $this->input->post('postcode2'),
							       'live_date' => $this->input->post('live_date'),
							      'stop_date' => $this->input->post('stop_date'),
							       'own' => $this->input->post('own'),
							       'rent' => $this->input->post('rent'),
							       'other' => $this->input->post('other'),
							       'i1' => $this->input->post('i1'),

							       'card_no' => $this->input->post('card_no'),
							      'authority' => $this->input->post('authority'),
							       'issue_date' => $this->input->post('issue_date'),
							       'expiry_date' => $this->input->post('expiry_date'),
							      'n1' => $this->input->post('n1'),
							       'nationality' => $this->input->post('nationality'),
							       'gname' => $this->input->post('gname'),
							      'lname' => $this->input->post('lname'),
							       'dob' => $this->input->post('dob'),
							       'nation' => $this->input->post('nation'),
							       'm1' => $this->input->post('m1'),
							       'ad1' => $this->input->post('ad1'),
							       'city12' => $this->input->post('city12'),
							      'state12' => $this->input->post('state12'),
							      'country12' => $this->input->post('country12'),

							      'postcode12' => $this->input->post('un_date'),
							      'mname' => $this->input->post('mname'),
							       'llname' => $this->input->post('llname'),
							       'mdob' => $this->input->post('mdob'),
							      'countryn' => $this->input->post('countryn'),
							       'mname1' => $this->input->post('mname1'),

							       'lname1' => $this->input->post('lname1'),
							       'mdob1' => $this->input->post('mdob1'),
							       'countryn1' => $this->input->post('countryn1'),
							       'l1' => $this->input->post('l1'),
							      't1' => $this->input->post('t1'),
							       'mbornnation' => $this->input->post('mbornnation'),
							       'fbornnation' => $this->input->post('fbornnation'),
							      'v1' => $this->input->post('v1'),
							       'time_uk' => $this->input->post('time_uk'),
							       'o1' => $this->input->post('o1'),
							      'dreason' => $this->input->post('dreason'),
							       'ddate' => $this->input->post('ddate'),
							       'dlong' => $this->input->post('dlong'),
							      'ddreason' => $this->input->post('ddreason'),
							       'dddate' => $this->input->post('dddate'),
							       'ddlong' => $this->input->post('ddlong'),
							      'dddreason' => $this->input->post('dddreason'),
							       'ddddate' => $this->input->post('ddddate'),
							       'dddlong' => $this->input->post('dddlong'),
							      'p1' => $this->input->post('p1'),
							       'q1' => $this->input->post('q1'),
							        'u1' => $this->input->post('u1'),
							       'travel' => $this->input->post('travel'),
							        'hospital' => $this->input->post('hospital'),
							       'addressp' => $this->input->post('addressp'),
							        'mdate' => $this->input->post('mdate'),
							       'msdate' => $this->input->post('msdate'),
							        'w1' => $this->input->post('w1'),
							       'ddpdate' => $this->input->post('ddpdate'),
							        'resultapp' => $this->input->post('resultapp'),
							       
							        'nino' => $this->input->post('nino'),
							       'd1' => $this->input->post('d1'),
							       'licno' => $this->input->post('licno'),
							       'f1' => $this->input->post('f1'),
							        'travel_tt' => $this->input->post('travel_tt'),
							       'rcountry' => $this->input->post('rcountry'),
							        'reason' => $this->input->post('reason'),
							       'dov' => $this->input->post('dov'),
							        'hhlong' => $this->input->post('hhlong'),
							       'scountry' => $this->input->post('scountry'),
							        'sreason' => $this->input->post('sreason'),
							       'sdov' => $this->input->post('sdov'),
							        'shlong' => $this->input->post('shlong'),
							       'h1' => $this->input->post('h1'),
							        'country34' => $this->input->post('country34'),
							       'reason34' => $this->input->post('reason34'),
							        'entrydate1' => $this->input->post('entrydate1'),
							       'exitdate1' => $this->input->post('exitdate1'),
							        'country343' => $this->input->post('country343'),
							       'reason343' => $this->input->post('reason343'),
							        'entrydate2' => $this->input->post('entrydate2'),
							       'exitdate2' => $this->input->post('exitdate2'),
							        'country3434' => $this->input->post('country3434'),
							       'reason3434' => $this->input->post('reason3434'),
							        'entrydate3' => $this->input->post('entrydate3'),
							       'exitdate3' => $this->input->post('exitdate3'),
							        'j1' => $this->input->post('j1'),
							       'licno1' => $this->input->post('licno1')


			
							    	             	);
				                	return $this->db->insert('tbl_user_details',$formarray);
				    }


				}





?>